### PR TITLE
also install xe(la)tex and metapost - needed by ACE docs

### PR DESCRIPTION
**Pull request by dimpase**

### CODE REVIEW

**Comment by dimpase** [comment]
@fingolfin

**Comment by dimpase** [comment]
This would fix https://github.com/gap-packages/ace/pull/36 docs building

**Comment by dimpase** [comment]
It's important that the tag `v1` is moved to the top commit here (or perhaps a new version, thus tag `v2` ?)

**Comment by dimpase** [comment]
Note that, AFIAK, tags cannot be managed by a PR, this is something to do after the merge.

**Comment by fingolfin** [comment]
First off, thank you for taking the time to make a PR!

Second, sorry for not replying before, but I didn't see it. GitHub Notifications are mostly useless, I get hundreds per day and can't read most of them for time reasons. If you want something, I recommend an email or a Slack notification)

Third, no, I don't think we want that. We don't want to install metapost for *everyone* just because ACE needs it. If ACE has special needs, then its action YAML should take care of them;

**Comment by dimpase** [comment]
oops, I completely forgot about this one. Have you looked at the ACE's PRs?

**Comment by dimpase** [comment]
> Third, no, I don't think we want that. We don't want to install metapost for _everyone_ just because ACE needs it. If ACE has special needs, then its action YAML should take care of them;

Can an action be named `gap-packages/ace/build-pkg-docs@v1`  instead of  `gap-actions/build-pkg-docs@v1` ?
This does not seem to be possible, as `build-pkg-docs` ought to be a separate repo name.

Can we have a new `gap-actions/build-pkg-docs-with-xetex-metafont@v1` ? This is something that would entail creating a new repo here. Can we have this? This is something that won't take much of mine or your time.

We can probably instead cram the whole `action.yaml` somewhere in ` gap-packages/ace/`, but this needs more time on my side.

**Comment by dimpase** [comment]
There are also actions with parameters. I guess one can modify this PR so that it installs that extra packages only when a parameter is specified.

**Pull request closed without merging**
